name: Docker Image CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Git Semantic Version
      uses: PaulHatch/semantic-version@v5.4.0
      id: version
      with:
        major_pattern: "major:"
        minor_pattern: "minor:"
        version_format: "${major}.${minor}.${patch}"
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        NEW_VERSION: ${{steps.version.outputs.version}}
      run: | 
        echo "Test $NEW_VERSION"
    # docker login -u $DOCKER_USER -p $DOCKER_PASSWOR 
    # - name: build docker image
    #   run: | 
    #     docker build -f Dockerfile -t tufik2/docker-graphql:${major}.${minor}.2 . --push
    #     docker build -f Dockerfile -t tufik2/docker-graphql:latest . --push
